### PR TITLE
Add fill properties.

### PR DESCRIPTION
**Pull request by H1Gdev**
Add fill properties for SVG. (vvvv/SVG#596)

- fill
- fill-opacity
- fill-rule

### CODE REVIEW

**Comment by H1Gdev** [comment]
Fix #5 issue.

**Comment by JsAndDotNet** [comment]
Am a bit busy at the minute, but I will review/merge this in a couple of weeks.

Thank you for doing this work.

**Comment by JsAndDotNet** [comment]
Snowed under due to corona stuff atm, but this will be reviewed and pulled when I can get round to it.

**Comment by JsAndDotNet** [comment]
Sorry, have been and still am rather ill. Have reviewed, but not merged yet. Want to do the publish to NuGet at the same and don't have the energy at the moment. Will sort it when I've recovered.

**Comment by H1Gdev** [comment]
Please take care of yourself !!

**Comment by JsAndDotNet** [comment]
Hi. I haven't forgotten this, but the merge is more likely to be near the end of the month/ early May. 

THIS PROJECT IS ACTIVE AND I WILL MERGE/ UPLOAD TO NUGET ONCE I'M BETTER.

**Comment by JsAndDotNet** [comment]
Now published to NuGet. Thanks @H1Gdev for the update.

**Pull request merged**
