### PR TITLE
Trim trailing spaces. Getting results with extra spaces, caused some confusion when checking for equality

### PR DESCRIPTION
**Pull request by bdawson82**

### CODE REVIEW

**Comment by JsAndDotNet** [comment]
Thanks for this and for making a separate PR to the other issue. 

As stated with the other PR, I'm currently ill and want to merge 3 PR's and publish to nuget in one go. Will hopefully be at the weekend.

**Comment by bdawson82** [comment]
No worries.  Thanks for the update.

**Comment by JsAndDotNet** [comment]
Hi. I haven't forgotten this, but the merge is more likely to be near the end of the month/ early May. 

THIS PROJECT IS ACTIVE AND I WILL MERGE/ UPLOAD TO NUGET ONCE I'M BETTER.

**Comment by JsAndDotNet** [comment]
I had accepted this, but it breaks a couple of the unit tests and I'm concerned about it breaking library users code, so will revert. 

I think it's a valid change, it's just that it's not really doing any harm and I don't want to break peoples tests that depend on this library.

**Pull request merged**
